//get all IO
GET http://localhost:3001/api/internalOrders HTTP/1.1
content-type: application/json
####
DELETE http://localhost:3001/api/internalOrders/2 HTTP/1.1
content-type: application/json
#####
       
GET http://localhost:3001/api/internalOrdersIssued  HTTP/1.1
content-type: application/json
#####
GET http://localhost:3001/api/internalOrdersAccepted  HTTP/1.1
content-type: application/json
#####

GET http://localhost:3001/api/internalOrders/4  HTTP/1.1
content-type: application/json


####

POST http://localhost:3001/api/internalOrders HTTP/1.1
content-type: application/json

{
   
    "products": [
        {
            "SKUId":13,
            "description":"a product",
            "price":10.99,
            "qty":3},
        {
            "SKUId":180,
            "description":"another product",
            "price":11.99,
            "qty":3}
        ],
    "customerId" : 1

}

########

PUT http://localhost:3001/api/internalOrders/4   HTTP/1.1
content-type: application/json


# {
#         "newState":"ACCEPTED"
#     }

{
    "newState":"COMPLETED",
    "products":[{"SkuID":13,"RFID":"12345678901234567890123456789016"},{"SkuID":180,"RFID":"12345678901234567890123456789038"}]
}


########
//post new returnOrder
POST http://localhost:3001/api/returnOrder HTTP/1.1
content-type: application/json

{
        "returnDate":"2021/11/29 09:33",
        "products": [{"SKUId":12,"description":"a product","price":10.99,"RFID":"12345678901234567890123456789016"},
                    {"SKUId":180,"description":"another product","price":11.99,"RFID":"12345678901234567890123456789038"}],
        "restockOrderId" : 1
    }


####
GET http://localhost:3001/api/returnOrder/5 HTTP/1.1
content-type: application/json
########
GET http://localhost:3001/api/returnOrders  HTTP/1.1
content-type: application/json

########
DELETE http://localhost:3001/api/returnOrder/1  HTTP/1.1
content-type: application/json

########
//post new restock order
POST http://localhost:3001/api/restockOrder HTTP/1.1
content-type: application/json

{
    "issueDate":"2021/11/29 09:33",
    "products": [{"SKUId":120,"description":"a product","price":10.99,"qty":6660},
                {"SKUId":180,"description":"another product","price":11.99,"qty":20}],
    "supplierId" : 1
}

########
GET http://localhost:3001/api/restockOrders  HTTP/1.1
content-type: application/json

########
GET http://localhost:3001/api/restockOrders/1  HTTP/1.1
content-type: application/json


########
GET http://localhost:3001/api/restockOrdersIssued  HTTP/1.1
content-type: application/json



########
//change status of restockorder
PUT http://localhost:3001/api/restockOrder/1   HTTP/1.1
content-type: application/json


{
        "newState":"DELIVERED"
    }


########
//change transportNode
PUT http://localhost:3001/api/restockOrder/1/transportNote   HTTP/1.1
content-type: application/json


{
       "transportNote":{"deliveryDate":"2023/6/29"}
}


########
GET http://localhost:3001/api/restockOrders/1/returnItems HTTP/1.1
content-type: application/json

########
//update skuitems
PUT http://localhost:3001/api/restockOrder/1/skuItems   HTTP/1.1
content-type: application/json

{
    "skuItems" : [{"SKUId":12,"rfid":"12345678901234567890123456789016"},{"SKUId":12,"rfid":"12345678901234567890123456789017"}]
}
